use crate::{
    arch::{memory_layout::PAGE_SIZE, time::get_ticks},
    mm::{MapPermission, MemorySet, UserBuffer},
    syscall::MmapFlags,
    utils::SysErrNo,
};

// 该文件创建形如/proc/xxx的文件
use super::*;
use alloc::{format, string::String, vec::Vec};

fn format_map_perm(perm: MapPermission, flags: MmapFlags) -> String {
    let mut s = String::with_capacity(4);
    s.push(if perm.contains(MapPermission::R) {
        'r'
    } else {
        '-'
    });
    s.push(if perm.contains(MapPermission::W) {
        'w'
    } else {
        '-'
    });
    s.push(if perm.contains(MapPermission::X) {
        'x'
    } else {
        '-'
    });
    s.push(if flags.contains(MmapFlags::MAP_SHARED) {
        's'
    } else {
        'p'
    });
    s
}

fn write_kernel_file(file: &dyn File, data: &mut String) -> Result<usize, SysErrNo> {
    let mut vec = Vec::new();
    unsafe {
        let bytes = data.as_bytes_mut();
        vec.push(core::slice::from_raw_parts_mut(
            bytes.as_mut_ptr(),
            bytes.len(),
        ));
    }
    file.write(UserBuffer::new(vec))
}

fn format_status(
    pid: usize,
    ppid: usize,
    comm: &str,
    memory_set: &MemorySet,
    real_uid: u32,
    effective_uid: u32,
    saved_uid: u32,
    real_gid: u32,
    effective_gid: u32,
    saved_gid: u32,
) -> String {
    let vm_size = memory_set.virtual_size_kb();
    let vm_rss = memory_set.resident_size_kb();
    format!(
        "Name:\t{}\n\
State:\tS (sleeping)\n\
Tgid:\t{}\n\
Pid:\t{}\n\
PPid:\t{}\n\
Uid:\t{}\t{}\t{}\t{}\n\
Gid:\t{}\t{}\t{}\t{}\n\
VmPeak:\t{:8} kB\n\
VmSize:\t{:8} kB\n\
VmHWM:\t{:8} kB\n\
VmRSS:\t{:8} kB\n\
VmSwap:\t       0 kB\n",
        comm,
        pid,
        pid,
        ppid,
        real_uid,
        effective_uid,
        saved_uid,
        effective_uid, // fs_uid defaults to effective_uid
        real_gid,
        effective_gid,
        saved_gid,
        effective_gid, // fs_gid defaults to effective_gid
        vm_size,
        vm_size,
        vm_rss,
        vm_rss,
    )
}

fn format_stat(pid: usize, ppid: usize, pgid: usize, state: char, comm: &str, memory_set: &MemorySet) -> String {
    let vsize = memory_set.virtual_size_kb() * 1024;
    let rss_pages = memory_set.resident_size_kb() * 1024 / PAGE_SIZE;
    format!(
        "{} ({}) {} {} {} 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 {} {} {} 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n",
        pid,
        comm,
        state,
        ppid,
        pgid,
        get_ticks(),
        vsize,
        rss_pages
    )
}

pub fn create_proc_dir_and_file(
    pid: usize,
    ppid: usize,
    pgid: usize,
    comm: &str,
    memory_set: &MemorySet,
    real_uid: u32,
    effective_uid: u32,
    saved_uid: u32,
    real_gid: u32,
    effective_gid: u32,
    saved_gid: u32,
) -> Result<(), SysErrNo> {
    let procdir = open(
        format!("/proc/{}", pid).as_str(),
        OpenFlags::O_DIRECTORY | OpenFlags::O_CREATE | OpenFlags::O_RDWR,
        DEFAULT_DIR_MODE,
    )?
    .file()?;
    // 强制刷盘确保目录创建持久化，否则后续在目录内创建的文件可能不可见
    procdir.inode.sync();

    //创建进程状态文件/proc/<pid>/stat
    let statfile = open(
        format!("/proc/{}/stat", pid).as_str(),
        OpenFlags::O_CREATE | OpenFlags::O_RDWR | OpenFlags::O_TRUNC,
        DEFAULT_FILE_MODE,
    )
    .unwrap()
    .file()?;
    let mut statinfo = format_stat(pid, ppid, pgid, 'S', comm, memory_set);
    write_kernel_file(statfile.as_ref(), &mut statinfo)?;
    statfile.inode.sync();

    //创建进程状态文件/proc/<pid>/status
    let statusfile = open(
        format!("/proc/{}/status", pid).as_str(),
        OpenFlags::O_CREATE | OpenFlags::O_RDWR | OpenFlags::O_TRUNC,
        DEFAULT_FILE_MODE,
    )?
    .file()?;
    let mut statusinfo =
        format_status(pid, ppid, comm, memory_set, real_uid, effective_uid, saved_uid, real_gid, effective_gid, saved_gid);
    write_kernel_file(statusfile.as_ref(), &mut statusinfo)?;
    statusfile.inode.sync();

    refresh_proc_maps(pid, memory_set)?;
    // Keep a zero-size directory entry for getdents-style proc enumeration.
    // Pagemap data itself is generated by PagemapFile when it is opened.
    let pagemapfile = open(
        format!("/proc/{}/pagemap", pid).as_str(),
        OpenFlags::O_CREATE | OpenFlags::O_RDWR,
        DEFAULT_FILE_MODE,
    )?
    .file()?;
    pagemapfile.inode.sync();

    Ok(())
}

/// Rebuild `/proc/<pid>/maps` from the process's current VMA metadata.
///
/// Proc files are regular VFS files in Ya2yOS, so their contents must be
/// refreshed before every open instead of being treated as a creation-time
/// snapshot. Copy VMA metadata before entering the filesystem to avoid
/// holding the address-space lock across VFS operations.
pub fn refresh_proc_maps(pid: usize, memory_set: &MemorySet) -> Result<(), SysErrNo> {
    let areas = {
        let memory_set = memory_set.get_ref();
        memory_set
            .areas
            .iter()
            .map(|area| {
                (
                    area.vpn_range.start().0 * PAGE_SIZE,
                    area.vpn_range.end().0 * PAGE_SIZE,
                    area.map_perm,
                    area.mmap_flags,
                    area.mmap_file.offset,
                    area.mmap_file.file.clone(),
                )
            })
            .collect::<Vec<_>>()
    };

    let mapsfile = open(
        format!("/proc/{}/maps", pid).as_str(),
        OpenFlags::O_CREATE | OpenFlags::O_RDWR | OpenFlags::O_TRUNC,
        DEFAULT_FILE_MODE,
    )?
    .file()?;
    let mut mapsinfo = String::new();
    for (start, end, perm, flags, offset, file) in areas {
        let pathname = file.map(|file| file.inode.path()).unwrap_or_default();
        mapsinfo.push_str(&format!(
            "{:x}-{:x} {} {:08x} 00:00 0 {}\n",
            start,
            end,
            format_map_perm(perm, flags),
            offset,
            pathname
        ));
    }
    write_kernel_file(mapsfile.as_ref(), &mut mapsinfo)?;
    mapsfile.inode.sync();
    Ok(())
}

pub fn refresh_proc_stat(
    pid: usize,
    ppid: usize,
    pgid: usize,
    state: char,
    comm: &str,
    memory_set: &MemorySet,
) -> Result<(), SysErrNo> {
    let statfile = open(
        format!("/proc/{}/stat", pid).as_str(),
        OpenFlags::O_CREATE | OpenFlags::O_RDWR | OpenFlags::O_TRUNC,
        DEFAULT_FILE_MODE,
    )?
    .file()?;
    let mut statinfo = format_stat(pid, ppid, pgid, state, comm, memory_set);
    write_kernel_file(statfile.as_ref(), &mut statinfo)?;
    statfile.inode.sync();
    Ok(())
}

pub fn refresh_proc_status(
    pid: usize,
    ppid: usize,
    comm: &str,
    memory_set: &MemorySet,
    real_uid: u32,
    effective_uid: u32,
    saved_uid: u32,
    real_gid: u32,
    effective_gid: u32,
    saved_gid: u32,
) -> Result<(), SysErrNo> {
    let statusfile = open(
        format!("/proc/{}/status", pid).as_str(),
        OpenFlags::O_CREATE | OpenFlags::O_RDWR | OpenFlags::O_TRUNC,
        DEFAULT_FILE_MODE,
    )?
    .file()?;
    let mut statusinfo =
        format_status(pid, ppid, comm, memory_set, real_uid, effective_uid, saved_uid, real_gid, effective_gid, saved_gid);
    write_kernel_file(statusfile.as_ref(), &mut statusinfo)?;
    statusfile.inode.sync();
    Ok(())
}

pub fn remove_proc_dir_and_file(pid: usize) {
    superblock_root_inode().unlink(format!("/proc/{}/pagemap", pid).as_str());
    FsIndex::remove_inode_idx(format!("/proc/{}/pagemap", pid).as_str());
    superblock_root_inode().unlink(format!("/proc/{}/maps", pid).as_str());
    FsIndex::remove_inode_idx(format!("/proc/{}/maps", pid).as_str());
    superblock_root_inode().unlink(format!("/proc/{}/status", pid).as_str());
    FsIndex::remove_inode_idx(format!("/proc/{}/status", pid).as_str());
    superblock_root_inode().unlink(format!("/proc/{}/stat", pid).as_str());
    FsIndex::remove_inode_idx(format!("/proc/{}/stat", pid).as_str());
    superblock_root_inode().unlink(format!("/proc/{}", pid).as_str());
    FsIndex::remove_inode_idx(format!("/proc/{}", pid).as_str());
}
