[package]
name = "os"
version = "0.1.0"
authors = [
    "Xiaojie Rao <202430691179@mail.scut.edu.cn>",
]
edition = "2021"

[dependencies]
buddy_system_allocator = "0.6"
bitflags = "1.2.1"
xmas-elf = "0.7.0"
virtio-drivers = "0.7.5"
lwext4_rust= {path = "../crates/lwext4_rust"}
log = "0.4"
kernel_guard = "0.1"
spin = "0.9.8"
hashbrown = "0.12.0"
num_enum = { version = "0.7.2", default-features = false }
cfg-if = { version = "1.0.0" }
event-listener = { version = "4.0", default-features = false }
smallvec = "1.15.1"
kspin = "0.1"
futures-util = { version = "0.3.32", default-features = false, features = ["async-await-macro"] }

smoltcp = { version = "0.13.1", default-features = false, features = [
    "alloc", "log", "medium-ethernet", "medium-ip", "proto-ipv4",
    "proto-ipv6", "socket-icmp", "socket-udp", "socket-tcp", "socket-raw", "async",
    "multicast",
] }

linux-raw-sys = { version = "0.12", default-features = false, features = [
    "no_std", "general", "net", "prctl", "system", "ioctl", "loop_device"
] }

# 架构特定依赖

# 当 target 为 riscv64 时自动引入
[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
sbi-rt = { version = "0.0.2", features = ["legacy"] }

# 当 target 为 loongarch64 时自动引入
[target.'cfg(target_arch = "loongarch64")'.dependencies]
loongArch64 = { git = "https://github.com/Godones/loongArch64" }

[build-dependencies]
cfg-if = { version = "1.0.0" }

[patch.crates-io]
cty = { path = "../crates/cty" }
smoltcp = { path = "vendor/smoltcp" }

[features]
default = ["net"]
error = []
warn = []
info = []
debug = []
trace = []
irq = []
net = []

# 这里不再需要 riscv64 = ["riscv", "sbi-rt"]，因为 target 会自动处理
# 但如果你代码里还在用 #[cfg(feature = "riscv64")]，建议改为 #[cfg(target_arch = "riscv64")]

[profile.release]
debug = true
panic = "abort"

[profile.dev]
panic = "abort"