//! Implementation of syscalls
//!
//! The single entry point to all system calls, [`syscall()`], is called
//! whenever userspace wishes to perform a system call using the `ecall`
//! instruction. In this case, the processor raises an 'Environment call from
//! U-mode' exception, which is handled as one of the cases in
//! [`crate::trap::trap_handler`].
//!
//! For clarity, each single syscall is implemented as its own function, named
//! `sys_` then the name of the syscall. You can find functions like this in
//! submodules, and you should also implement syscalls this way.
use core::arch;

use linux_raw_sys::general::{clone_args, open_how, statx};
#[cfg(feature = "net")]
use linux_raw_sys::net::{msghdr, socklen_t};
use log::{error, warn};
use num_enum::FromPrimitive;
#[derive(Debug, PartialEq, FromPrimitive)]
#[repr(usize)]
pub enum Syscall {
    IoSetup = 0,
    IoDestroy = 1,
    IoSubmit = 2,
    IoCancel = 3,
    IoGetEvents = 4,
    Setxattr = 5,
    Lsetxattr = 6,
    Fsetxattr = 7,
    Getxattr = 8,
    Lgetxattr = 9,
    Fgetxattr = 10,
    Listxattr = 11,
    Llistxattr = 12,
    Flistxattr = 13,
    Removexattr = 14,
    Lremovexattr = 15,
    Fremovexattr = 16,
    Getcwd = 17,
    Eventfd2 = 19,
    EpollCreate1 = 20,
    EpollCtl = 21,
    EpollPwait = 22,
    Dup = 23,
    Dup3 = 24,
    Fcntl = 25,
    InotifyInit1 = 26,
    InotifyAddWatch = 27,
    InotifyRmWatch = 28,
    Ioctl = 29,
    Flock = 32,
    Mknodat = 33,
    Mkdirat = 34,
    Unlinkat = 35,
    Symlinkat = 36,
    Linkat = 37,
    Renameat = 38,
    Umount2 = 39,
    Mount = 40,
    PivotRoot = 41,
    StatFs = 43,
    FstatFs = 44,
    Truncate = 45,
    Ftruncate = 46,
    Fallocate = 47,
    Faccessat = 48,
    Chdir = 49,
    Chroot = 51,
    Fchmod = 52,
    Fchmodat = 53,
    Fchownat = 54,
    Fchown = 55,
    Openat = 56,
    Close = 57,
    Vhangup = 58,
    Pipe2 = 59,
    Getdents64 = 61,
    Lseek = 62,
    Read = 63,
    Write = 64,
    Readv = 65,
    Writev = 66,
    Pread64 = 67,
    Pwrite64 = 68,
    Preadv = 69,
    Pwritev = 70,
    SendFile = 71,
    Pselect6 = 72,
    Ppoll = 73,
    Signalfd4 = 74,
    Vmsplice = 75,
    Splice = 76,
    Tee = 77,
    ReadLinkat = 78,
    Fstatat = 79,
    Fstat = 80,
    Sync = 81,
    Fsync = 82,
    Fdatasync = 83,
    SyncFileRange = 84,
    TimerfdCreate = 85,
    TimerfdSettime = 86,
    TimerfdGettime = 87,
    Utimensat = 88,
    Acct = 89,
    Capget = 90,
    Capset = 91,
    Personality = 92,
    Exit = 93,
    ExitGroup = 94,
    WaitId = 95,
    SetTidAddress = 96,
    Unshare = 97,
    Futex = 98,
    SetRobustList = 99,
    GetRobustList = 100,
    NanoSleep = 101,
    GetTimer = 102,
    SetTimer = 103,
    InitModule = 105,
    DeleteModule = 106,
    TimerCreate = 107,
    TimerDelete = 111,
    ClockSetTime = 112,
    ClockGettime = 113,
    ClockGetres = 114,
    ClockNanosleep = 115,
    SysLog = 116,
    SchedSetScheduler = 119,
    SchedGetScheduler = 120,
    SchedGetParam = 121,
    SchedSetaffinity = 122,
    SchedGetaffinity = 123,
    SchedYield = 124,
    SchedGetPriorityMax = 125,
    SchedGetPriorityMin = 126,
    SigKill = 129,
    Tkill = 130,
    Tgkill = 131,
    SigSuspend = 133,
    SigAction = 134,
    SigProcMask = 135,
    SigPending = 136,
    SigTimedWait = 137,
    SigReturn = 139,
    Setpriority = 140,
    Getpriority = 141,
    Setregid = 143,
    Setgid = 144,
    Setreuid = 145,
    Setuid = 146,
    Setresuid = 147,
    GetResuid = 148,
    SetResgid = 149,
    GetResgid = 150,
    Setfsuid = 151,
    Setfsgid = 152,
    Times = 153,
    SetPGid = 154,
    GetPGid = 155,
    SetSid = 157,
    GetGroup = 158,
    SetGroup = 159,
    Uname = 160,
    Setdomainname = 162,
    Getrlimit = 163,
    Setrlimit = 164,
    GetRusage = 165,
    Umask = 166,
    Prctl = 167,
    GetCpu = 168,
    GetTimeOfDay = 169,
    SetTimeOfDay = 170,
    Adjtimex = 171,
    GetPid = 172,
    GetPPid = 173,
    GetUid = 174,
    GetEUid = 175,
    GetGid = 176,
    GetEGid = 177,
    GetTid = 178,
    SysInfo = 179,
    MqOpen = 180,
    MqUnlink = 181,
    MqTimedSend = 182,
    MqTimedReceive = 183,
    MqNotify = 184,
    MsgGet = 186,
    MsgSnd = 187,
    MsgRcv = 188,
    MsgCtl = 189,
    Shmget = 194,
    Shmctl = 195,
    Shmat = 196,
    Shmdt = 197,
    Socket = 198,
    Socketpair = 199,
    Bind = 200,
    Listen = 201,
    Accept = 202,
    Connect = 203,
    GetSockName = 204,
    GetPeerName = 205,
    SendTo = 206,
    RecvFrom = 207,
    SetSockOpt = 208,
    GetSockOpt = 209,
    Shutdown = 210,
    SendMsg = 211,
    RecvMsg = 212,
    Brk = 214,
    Munmap = 215,
    Mremap = 216,
    AddKey = 217,
    RequestKey = 218,
    Keyctl = 219,
    Clone = 220,
    Execve = 221,
    Mmap = 222,
    Fadvise64 = 223,
    Swapon = 224,
    Swapoff = 225,
    Mprotect = 226,
    MSync = 227,
    Mlock = 228,
    Munlock = 229,
    Mlockall = 230,
    Munlockall = 231,
    Mincore = 232,
    Madvise = 233,
    GetMempolicy = 236,
    SetMempolicy = 237,
    PerfEventOpen = 241,
    Accept4 = 242,
    Wait4 = 260,
    Prlimit = 261,
    FanotifyInit = 262,
    NameToHandleAt = 264,
    OpenByHandleAt = 265,
    ClockAdjtime = 266,
    Kcmp = 272,
    Renameat2 = 276,
    Getrandom = 278,
    MemfdCreate = 279,
    Bpf = 280,
    UserFaultfd = 282,
    MemBarrier = 283,
    Mlock2 = 284,
    CopyFileRange = 285,
    Preadv2 = 286,
    Pwritev2 = 287,
    Statx = 291,
    IoUringSetup = 425,
    OpenTree = 428,
    MoveMount = 429,
    Fsopen = 430,
    Fsconfig = 431,
    FsMount = 432,
    Fspick = 433,
    PidfdOpen = 434,
    Clone3 = 435,
    CloseRange = 436,
    Openat2 = 437,
    PidfdGetfd = 438,
    Faccessat2 = 439,
    EpollPwait2 = 441,
    MountSetattr = 442,
    MemfdSecret = 447,
    FutexWaitv = 449,
    FutexWait = 455,
    MachineShutdown = 1000,
    #[num_enum(default)]
    Default = 9999,
}

mod fs;
mod io_mpx;
mod mm;
#[cfg(feature = "net")]
mod net;
mod options;
mod resource;
mod signal;
mod sync;
mod sys;
mod task;
mod time;

use crate::task::{current_task, sys_futex};
use crate::utils::SysErrNo;
use crate::{
    arch::cpu::shutdown,
    fs::{Kstat, Statfs},
    signal::{SigAction, SigInfo, SigSet},
    timer::{Itimerval, Rusage, TimeVal, Timespec, Timex, Tms},
    utils::SyscallRet,
};
use fs::*;
use io_mpx::*;
use mm::*;
#[cfg(feature = "net")]
use net::*;
pub use options::{
    FaccessatFileMode, FutexCmd, FutexOpt, MmapFlags, MmapProt, PollEvents, RLimit, SignalMaskFlag,
    Utsname,
};
use resource::*;
use signal::*;
use sync::*;
use sys::*;
pub use task::*;
use time::*;

/// handle syscall exception with `syscall_id` and other arguments
pub fn syscall(syscall_id: usize, args: [usize; 6]) -> SyscallRet {
    let id = syscall_id;
    let syscall_id: Syscall = Syscall::from(syscall_id);
    log::debug!(
        "[syscall begin] {:?} sepc = {:#x}",
        syscall_id,
        current_task().unwrap().inner_lock().trap_cx().get_sepc()
    );
    match syscall_id {
        // Xattr
        Syscall::Setxattr => sys_setxattr(args[0], args[1], args[2], args[3], args[4]),
        Syscall::Lsetxattr => sys_lsetxattr(args[0], args[1], args[2], args[3], args[4]),
        Syscall::Fsetxattr => sys_fsetxattr(args[0], args[1], args[2], args[3], args[4]),
        Syscall::Getxattr => sys_getxattr(args[0], args[1], args[2], args[3]),
        Syscall::Lgetxattr => sys_lgetxattr(args[0], args[1], args[2], args[3]),
        Syscall::Fgetxattr => sys_fgetxattr(args[0], args[1], args[2], args[3]),
        Syscall::Listxattr => sys_listxattr(args[0], args[1], args[2]),
        Syscall::Llistxattr => sys_llistxattr(args[0], args[1], args[2]),
        Syscall::Flistxattr => sys_flistxattr(args[0], args[1], args[2]),
        Syscall::Removexattr => sys_removexattr(args[0], args[1]),
        Syscall::Lremovexattr => sys_removexattr(args[0], args[1]),
        Syscall::Fremovexattr => sys_removexattr(args[0], args[1]),

        Syscall::Getcwd => sys_getcwd(args[0] as *const u8, args[1]),
        // event
        Syscall::Eventfd2 => sys_eventfd2(args[0] as u32, args[1] as u32),
        Syscall::TimerfdCreate => sys_timerfd_create(args[0] as u32, args[1] as u32),
        Syscall::TimerfdSettime => sys_timerfd_settime(
            args[0] as u32,
            args[1] as u32,
            args[2] as *const u8,
            args[3] as *mut u8,
        ),
        Syscall::TimerfdGettime => sys_timerfd_gettime(args[0] as u32, args[1] as *mut u8),
        Syscall::InotifyInit1 => sys_inotify_init1(args[0] as u32),
        Syscall::InotifyAddWatch => {
            sys_inotify_add_watch(args[0] as i32, args[1] as *const u8, args[2] as u32)
        }
        Syscall::InotifyRmWatch => sys_inotify_rm_watch(args[0] as i32, args[1] as i32),

        Syscall::Dup => sys_dup(args[0]),
        Syscall::Dup3 => sys_dup3(args[0], args[1], args[2] as u32),
        Syscall::Fcntl => sys_fcntl(args[0], args[1], args[2]),
        Syscall::Flock => sys_flock(args[0] as i32, args[1] as i32),
        Syscall::Mknodat => sys_mknodat(args[0] as i32, args[1], args[2], args[3]),
        Syscall::Ioctl => sys_ioctl(args[0], args[1], args[2]),
        Syscall::Mkdirat => sys_mkdirat(args[0] as isize, args[1] as *const u8, args[2] as u32),
        Syscall::Unlinkat => sys_unlinkat(args[0] as isize, args[1] as *const u8, args[2] as u32),
        Syscall::Symlinkat => {
            sys_symlinkat(args[0] as *const u8, args[1] as isize, args[2] as *const u8)
        }
        Syscall::Linkat => sys_linkat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as isize,
            args[3] as *const u8,
            args[4] as u32,
        ),
        Syscall::Renameat => sys_renameat2(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as isize,
            args[3] as *const u8,
            0u32,
        ),
        Syscall::Umount2 => sys_umount2(args[0] as *const u8, args[1] as u32),
        Syscall::Mount => sys_mount(
            args[0] as *const u8,
            args[1] as *const u8,
            args[2] as *const u8,
            args[3] as u32,
            args[4] as *const u8,
        ),
        Syscall::PivotRoot => sys_pivot_root(args[0], args[1]),

        Syscall::StatFs => sys_statfs(args[0] as *const u8, args[1] as *mut Statfs),
        Syscall::FstatFs => sys_fstatfs(args[0] as i32, args[1]),
        Syscall::Ftruncate => sys_ftruncate(args[0], args[1] as i32),
        Syscall::Fallocate => sys_fallocate(
            args[0] as usize,
            args[1] as u32,
            args[2] as usize,
            args[3] as usize,
        ),
        Syscall::Faccessat => sys_faccessat(
            args[0] as i32,
            args[1] as *const u8,
            args[2] as u32,
            args[3],
        ),
        Syscall::Chdir => sys_chdir(args[0] as *const u8),
        Syscall::Fchmod => sys_fchmod(args[0] as usize, args[1] as u32),
        Syscall::Fchmodat => sys_fchmodat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as u32,
            args[3] as u32,
        ),
        Syscall::Fchownat => sys_fchownat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as usize,
            args[3] as usize,
            args[4] as u32,
        ),
        Syscall::Fchown => sys_fchown(args[0], args[1], args[2]),
        Syscall::Openat => sys_openat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as u32,
            args[3] as u32,
        ),
        Syscall::Close => sys_close(args[0]),
        Syscall::CloseRange => sys_close_range(args[0] as u32, args[1] as u32, args[2] as u32),
        Syscall::Openat2 => sys_openat2(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as *const open_how,
            args[3],
        ),
        Syscall::Pipe2 => sys_pipe2(args[0] as *mut u32),
        Syscall::Getdents64 => sys_getdents64(args[0], args[1] as *const u8, args[2]),
        Syscall::Lseek => sys_lseek(args[0], args[1] as isize, args[2]),
        Syscall::Read => sys_read(args[0], args[1] as *const u8, args[2]),
        Syscall::Write => sys_write(args[0], args[1] as *const u8, args[2]),
        Syscall::Readv => sys_readv(args[0], args[1] as *const u8, args[2]),
        Syscall::Writev => sys_writev(args[0], args[1] as *const u8, args[2]),
        Syscall::Preadv => sys_preadv2(args[0], args[1] as *const u8, args[2], args[3], args[4], 0),
        Syscall::Pwritev => {
            sys_pwritev2(args[0], args[1] as *const u8, args[2], args[3], args[4], 0)
        }
        Syscall::Preadv2 => sys_preadv2(
            args[0],
            args[1] as *const u8,
            args[2],
            args[3],
            args[4],
            args[5] as u32,
        ),
        Syscall::Pwritev2 => sys_pwritev2(
            args[0],
            args[1] as *const u8,
            args[2],
            args[3],
            args[4],
            args[5] as u32,
        ),
        Syscall::Pread64 => sys_pread64(args[0], args[1] as *const u8, args[2], args[3] as isize),
        Syscall::Pwrite64 => sys_pwrite64(args[0], args[1] as *const u8, args[2], args[3] as isize),
        Syscall::SendFile => sys_sendfile(args[0], args[1], args[2], args[3]),
        Syscall::Pselect6 => sys_pselect6(args[0], args[1], args[2], args[3], args[4], args[5]),
        Syscall::Ppoll => sys_ppoll(args[0], args[1], args[2], args[3]),
        Syscall::Signalfd4 => sys_signalfd4(args[0] as u32, args[1] as *const u8, args[2] as u32),
        Syscall::Vmsplice => sys_vmsplice(args[0] as i32, args[1], args[2] as u32, args[3] as u32),
        Syscall::Splice => sys_splice(
            args[0] as i32,
            args[1] as *const i64,
            args[2] as i32,
            args[3] as *const i64,
            args[4],
            args[5] as u32,
        ),
        Syscall::Tee => sys_tee(args[0] as i32, args[1] as i32, args[2], args[3] as u32),
        Syscall::ReadLinkat => sys_readlinkat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as *const u8,
            args[3],
        ),
        Syscall::Fstatat => sys_fstatat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as *mut Kstat,
            args[3],
        ),
        Syscall::Fstat => sys_fstat(args[0], args[1] as *mut Kstat),
        Syscall::Statx => sys_statx(
            args[0] as isize,
            args[1] as *const u8,
            args[2],
            args[3] as u32,
            args[4] as *mut statx,
        ),
        Syscall::Sync => sys_sync(),
        Syscall::Fsync => sys_fsync(args[0]),
        Syscall::Fdatasync => sys_fdatasync(args[0]),
        Syscall::SyncFileRange => sys_sync_file_range(
            args[0] as i32,
            args[1] as i64,
            args[2] as i64,
            args[3] as u32,
        ),
        Syscall::Utimensat => sys_utimensat(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as *const Timespec,
            args[3],
        ),
        Syscall::Exit => sys_exit(args[0] as i32),
        Syscall::ExitGroup => sys_exit_group(args[0] as i32),
        Syscall::Futex => sys_futex(
            args[0] as *mut i32,
            args[1] as u32,
            args[2] as i32,
            args[3] as *const Timespec,
            args[4] as *mut u32,
            args[5] as i32,
        ),
        Syscall::SetRobustList => sys_set_robust_list(args[0], args[1]),
        Syscall::GetRobustList => {
            sys_get_robust_list(args[0], args[1] as *mut usize, args[2] as *mut usize)
        }
        Syscall::NanoSleep => sys_nanosleep(args[0] as *const Timespec, args[1] as *mut Timespec),
        Syscall::GetTimer => sys_gettimer(args[0] as i32, args[1]),
        Syscall::SetTimer => sys_settimer(
            args[0] as usize,
            args[1] as *const Itimerval,
            args[2] as *mut Itimerval,
        ),
        Syscall::ClockSetTime => sys_clock_settime(args[0] as u32, args[1] as *const Timespec),
        Syscall::ClockGettime => sys_clock_gettime(args[0], args[1] as *mut Timespec),
        Syscall::ClockGetres => sys_clock_getres(args[0] as isize, args[1]),
        Syscall::ClockNanosleep => sys_clock_nanosleep(
            args[0],
            args[1] as u32,
            args[2] as *const Timespec,
            args[3] as *mut Timespec,
        ),
        Syscall::SysLog => sys_syslog(args[0] as isize, args[1] as *const u8, args[2]),
        Syscall::InitModule => sys_init_module(args[0] as *const u8, args[1], args[2] as *const u8),
        Syscall::DeleteModule => sys_delete_module(args[0] as *const u8, args[1] as u32),
        Syscall::TimerCreate => {
            sys_timer_create(args[0] as i32, args[1] as *const u8, args[2] as *mut u32)
        }
        Syscall::TimerDelete => sys_timer_delete(args[0]),
        Syscall::SchedSetScheduler => {
            sys_sched_setscheduler(args[0], args[1], args[2] as *const u8)
        }
        Syscall::SchedGetScheduler => sys_sched_getscheduler(args[0]),
        Syscall::SchedGetParam => sys_sched_getparam(args[0], args[1] as *mut u8),
        Syscall::SchedSetaffinity => sys_sched_setaffinity(args[0], args[1], args[2]),
        Syscall::SchedGetaffinity => sys_sched_getaffinity(args[0], args[1], args[2]),
        Syscall::SchedYield => sys_sched_yield(),
        Syscall::SchedGetPriorityMax => sys_sched_get_priority_max(args[0] as i32),
        Syscall::SchedGetPriorityMin => sys_sched_get_priority_min(args[0] as i32),

        Syscall::SigKill => sys_kill(args[0] as isize, args[1]),
        Syscall::Tkill => sys_tkill(args[0], args[1]),
        Syscall::Tgkill => sys_tgkill(args[0], args[1], args[2]),
        Syscall::SigSuspend => sys_rt_sigsuspend(args[0] as *const SigSet),
        Syscall::SigAction => sys_rt_sigaction(
            args[0],
            args[1] as *const SigAction,
            args[2] as *mut SigAction,
        ),
        Syscall::SigProcMask => sys_rt_sigprocmask(
            args[0] as u32,
            args[1] as *const SigSet,
            args[2] as *mut SigSet,
        ),
        Syscall::SigPending => sys_rt_sigpending(args[0]),
        Syscall::SigTimedWait => sys_rt_sigtimedwait(
            args[0] as *const SigSet,
            args[1] as *mut SigInfo,
            args[2] as *const Timespec,
        ),
        Syscall::SigReturn => sys_rt_sigreturn(),
        Syscall::Setreuid => sys_setreuid(args[0], args[1]),
        Syscall::Setuid => sys_setuid(args[0] as usize),
        Syscall::Setresuid => sys_setresuid(args[0] as u32, args[1] as u32, args[2] as u32),
        Syscall::GetResuid => sys_getresuid(
            args[0] as *mut u32,
            args[1] as *mut u32,
            args[2] as *mut u32,
        ),
        Syscall::Setregid => sys_setregid(args[0], args[1]),
        Syscall::Setgid => sys_setgid(args[0]),
        Syscall::SetResgid => sys_setresgid(args[0] as u32, args[1] as u32, args[2] as u32),
        Syscall::GetResgid => sys_getresgid(
            args[0] as *mut u32,
            args[1] as *mut u32,
            args[2] as *mut u32,
        ),
        Syscall::Times => sys_times(args[0] as *mut Tms),
        Syscall::SetPGid => sys_setpgid(args[0] as u32, args[1] as u32),
        Syscall::GetPGid => sys_getpgid(args[0] as u32),
        Syscall::SetSid => sys_setsid(),
        Syscall::GetGroup => sys_getgroups(args[0], args[1] as *mut u32),
        Syscall::SetGroup => sys_setgroups(args[0], args[1] as *const u32),
        Syscall::GetRusage => sys_getrusage(args[0] as isize, args[1] as *mut Rusage),
        Syscall::GetCpu => sys_getcpu(args[0] as *mut u32, args[1] as *mut u32, args[2] as *mut u8),
        Syscall::GetTimeOfDay => sys_gettimeofday(args[0] as *mut TimeVal, args[1] as usize),
        Syscall::SetTimeOfDay => sys_settimeofday(args[0] as *const TimeVal, args[1] as *const u8),
        Syscall::Adjtimex => sys_adjtimex(args[0] as *mut Timex),
        Syscall::ClockAdjtime => sys_clock_adjtime(args[0] as u32, args[1] as *mut Timex),
        Syscall::Uname => sys_uname(args[0] as *mut u8),
        Syscall::Setdomainname => sys_setdomainname(args[0] as *const u8, args[1]),
        Syscall::GetPid => sys_getpid(),
        Syscall::GetPPid => sys_getppid(),
        Syscall::GetUid => sys_getuid(),
        Syscall::GetEUid => sys_geteuid(),
        Syscall::GetGid => sys_getgid(),
        Syscall::GetEGid => sys_getegid(),
        Syscall::GetTid => sys_gettid(),
        Syscall::SysInfo => sys_sysinfo(args[0] as *const u8),
        Syscall::MqOpen => sys_mq_open(
            args[0] as *const u8,
            args[1] as i32,
            args[2] as u32,
            args[3] as *const u8,
        ),
        Syscall::MqUnlink => sys_mq_unlink(args[0] as *const u8),
        Syscall::MqTimedSend => sys_mq_timedsend(
            args[0] as usize,
            args[1] as *const u8,
            args[2],
            args[3] as u32,
            args[4] as *const u8,
        ),
        Syscall::MqTimedReceive => sys_mq_timedreceive(
            args[0] as usize,
            args[1] as *mut u8,
            args[2],
            args[3] as *mut u32,
            args[4] as *const u8,
        ),
        Syscall::MqNotify => sys_mq_notify(args[0] as usize, args[1] as *const u8),
        Syscall::MsgGet => sys_msgget(args[0] as i32, args[1] as i32),
        Syscall::MsgSnd => sys_msgsnd(
            args[0] as i32,
            args[1] as *const u8,
            args[2],
            args[3] as i32,
        ),
        Syscall::MsgRcv => sys_msgrcv(
            args[0] as i32,
            args[1] as *mut u8,
            args[2],
            args[3] as i64,
            args[4] as i32,
        ),
        Syscall::MsgCtl => sys_msgctl(args[0] as i32, args[1] as i32, args[2] as *mut u8),
        Syscall::Shmget => sys_shmget(args[0] as i32, args[1], args[2] as i32),
        Syscall::Shmctl => sys_shmctl(args[0] as i32, args[1] as i32, args[2]),
        Syscall::Shmat => sys_shmat(args[0] as i32, args[1], args[2] as i32),
        #[cfg(feature = "net")]
        Syscall::Socket => sys_socket(args[0] as u32, args[1] as u32, args[2] as u32),
        #[cfg(feature = "net")]
        Syscall::Socketpair => sys_socketpair(
            args[0] as u32,
            args[1] as u32,
            args[2] as u32,
            args[3] as *mut u32,
        ),
        #[cfg(feature = "net")]
        Syscall::Bind => sys_bind(args[0], args[1] as *const u8, args[2] as u32),
        #[cfg(feature = "net")]
        Syscall::Listen => sys_listen(args[0], args[1] as u32),
        #[cfg(feature = "net")]
        Syscall::Accept => sys_accept(args[0], args[1] as *mut u8, args[2] as u32),
        #[cfg(feature = "net")]
        Syscall::Connect => sys_connect(args[0], args[1] as *const u8, args[2] as u32),
        #[cfg(feature = "net")]
        Syscall::GetSockName => sys_getsockname(args[0], args[1] as *const u8, args[2]),
        #[cfg(feature = "net")]
        Syscall::GetPeerName => sys_getpeername(args[0], args[1] as *const u8, args[2]),
        #[cfg(feature = "net")]
        Syscall::SendTo => sys_sendto(
            args[0],
            args[1] as *const u8,
            args[2],
            args[3] as u32,
            args[4] as *const u8,
            args[5] as u32,
        ),
        #[cfg(feature = "net")]
        Syscall::RecvFrom => sys_recvfrom(
            args[0],
            args[1] as *mut u8,
            args[2],
            args[3] as u32,
            args[4] as *mut u8,
            args[5] as *mut socklen_t,
        ),
        #[cfg(feature = "net")]
        Syscall::SetSockOpt => sys_setsockopt(
            args[0],
            args[1] as u32,
            args[2] as u32,
            args[3] as *const u8,
            args[4] as u32,
        ),
        #[cfg(feature = "net")]
        Syscall::GetSockOpt => sys_getsockopt(
            args[0],
            args[1] as u32,
            args[2] as u32,
            args[3] as *mut u8,
            args[4] as *mut socklen_t,
        ),
        #[cfg(feature = "net")]
        Syscall::Shutdown => sys_shutdown(args[0], args[1] as u32),
        #[cfg(feature = "net")]
        Syscall::SendMsg => sys_sendmsg(args[0], args[1] as *const msghdr, args[2] as u32),
        #[cfg(feature = "net")]
        Syscall::RecvMsg => sys_recvmsg(args[0], args[1] as *mut msghdr, args[2] as u32),
        #[cfg(feature = "net")]
        Syscall::Accept4 => sys_accept4(
            args[0] as usize,
            args[1] as *mut u8,
            args[2] as u32,
            args[3] as u32,
        ),
        Syscall::Clone => sys_clone(args[0], args[1], args[2], args[3], args[4]),
        Syscall::Clone3 => sys_clone3(args[0] as *const clone_args, args[1]),
        Syscall::Brk => sys_brk(args[0]),

        Syscall::Mmap => sys_mmap(
            args[0],
            args[1],
            args[2] as u32,
            args[3] as u32,
            args[4],
            args[5],
        ),
        Syscall::Munmap => sys_munmap(args[0], args[1]),
        Syscall::Mremap => sys_mremap(args[0], args[1], args[2], args[3] as i32, args[4]),
        Syscall::AddKey => sys_add_key(
            args[0] as *const u8,
            args[1] as *const u8,
            args[2] as *const u8,
            args[3],
            args[4] as isize,
        ),
        Syscall::RequestKey => sys_request_key(
            args[0] as *const u8,
            args[1] as *const u8,
            args[2] as *const u8,
            args[3] as isize,
        ),
        Syscall::Keyctl => sys_keyctl(args[0], args[1], args[2], args[3], args[4]),
        Syscall::Mprotect => sys_mprotect(args[0], args[1], args[2] as u32),
        Syscall::Mlock => sys_mlock(args[0], args[1]),
        Syscall::Munlock => sys_munlock(args[0], args[1]),
        Syscall::Mlockall => sys_mlockall(args[0] as i32),
        Syscall::Munlockall => sys_munlockall(),
        Syscall::Mlock2 => sys_mlock2(args[0], args[1], args[2] as i32),
        Syscall::Mincore => sys_mincore(args[0], args[1], args[2] as *mut u8),
        Syscall::MSync => Ok(0),
        Syscall::Madvise => sys_madvise(args[0], args[1], args[2]),
        Syscall::WaitId => sys_waitid(
            args[0] as i32,
            args[1] as i32,
            args[2] as *mut SigInfo,
            args[3] as i32,
        ),
        Syscall::Wait4 => sys_waitpid(args[0] as i32, args[1] as *mut i32, args[2] as u32),

        Syscall::Renameat2 => sys_renameat2(
            args[0] as isize,
            args[1] as *const u8,
            args[2] as isize,
            args[3] as *const u8,
            args[4] as u32,
        ),
        Syscall::Getrandom => sys_getrandom(args[0] as *const u8, args[1], args[2] as u32),
        Syscall::MemBarrier => Ok(0),
        Syscall::CopyFileRange => {
            sys_copy_file_range(args[0], args[1], args[2], args[3], args[4], args[5] as u32)
        }
        Syscall::EpollCreate1 => sys_epoll_create1(args[0] as u32),
        Syscall::EpollCtl => sys_epoll_ctl(args[0], args[1], args[2], args[3]),
        Syscall::EpollPwait => sys_epoll_pwait(args[0], args[1], args[2], args[3], args[4]),
        Syscall::MachineShutdown => shutdown(false),

        // task ops
        Syscall::Execve => sys_execve(
            args[0] as *const u8,
            args[1] as *const usize,
            args[2] as *const usize,
        ),
        Syscall::SetTidAddress => sys_settidaddress(args[0]),
        Syscall::Unshare => sys_unshare(args[0] as i32),
        Syscall::Getpriority => sys_getpriority(args[0] as i32, args[1]),
        Syscall::Setpriority => sys_setpriority(args[0] as i32, args[1], args[2] as i32),
        Syscall::Getrlimit => sys_getrlimit(args[0] as i32, args[1]),
        Syscall::Setrlimit => sys_setrlimit(args[0] as i32, args[1]),
        Syscall::Prlimit => sys_prlimit(
            args[0],
            args[1] as u32,
            args[2] as *const RLimit,
            args[3] as *mut RLimit,
        ),
        Syscall::Kcmp => sys_kcmp(args[0], args[1], args[2] as i32, args[3], args[4]),
        Syscall::Umask => sys_umask(args[0] as u32),
        Syscall::GetMempolicy => sys_get_mempolicy(args[0], args[1], args[2], args[3], args[4]),
        Syscall::SetMempolicy => sys_set_mempolicy(args[0] as i32, args[1], args[2]),

        // pidfd
        Syscall::PidfdOpen => sys_pidfd_open(args[0] as u32, args[1] as u32),
        Syscall::PidfdGetfd => sys_pidfd_getfd(args[0] as i32, args[1] as i32, args[2] as u32),
        Syscall::MountSetattr => sys_mount_setattr(
            args[0] as i32,
            args[1] as *const u8,
            args[2] as u32,
            args[3] as usize,
            args[4],
        ),

        // dummy fds
        Syscall::FanotifyInit => sys_fanotify_init(args[0] as u32, args[1] as u32),
        Syscall::NameToHandleAt => sys_name_to_handle_at(
            args[0] as i32,
            args[1] as *const u8,
            args[2] as *mut u8,
            args[3] as *mut i32,
            args[4] as u32,
        ),
        Syscall::OpenByHandleAt => {
            sys_open_by_handle_at(args[0] as i32, args[1] as *mut u8, args[2] as u32)
        }
        Syscall::MemfdCreate => sys_memfd_create(args[0] as *const u8, args[1] as u32),
        Syscall::Bpf => sys_bpf(args[0] as i32, args[1] as *mut u8, args[2] as u32),
        Syscall::UserFaultfd => sys_user_faultfd(args[0] as u32),
        Syscall::PerfEventOpen => sys_perf_event_open(
            args[0] as *mut u8,
            args[1] as u32,
            args[2] as i32,
            args[3] as i32,
            args[4] as u32,
        ),
        Syscall::IoUringSetup => sys_io_uring_setup(args[0] as u32, args[1] as *mut u8),
        Syscall::OpenTree => sys_open_tree(args[0] as i32, args[1] as *const u8, args[2] as u32),
        Syscall::MoveMount => sys_move_mount(
            args[0] as i32,
            args[1] as *const u8,
            args[2] as i32,
            args[3] as *const u8,
            args[4] as u32,
        ),
        Syscall::Fsopen => sys_fsopen(args[0] as *const u8, args[1] as u32),
        Syscall::Fsconfig => sys_fsconfig(
            args[0] as i32,
            args[1] as u32,
            args[2],
            args[3],
            args[4] as i32,
        ),
        Syscall::FsMount => sys_fsmount(args[0] as i32, args[1] as u32, args[2] as u32),
        Syscall::Fspick => sys_fspick(args[0] as i32, args[1] as *mut u8, args[2] as u32),
        Syscall::MemfdSecret => sys_memfd_secret(args[0] as u32),
        Syscall::Acct => sys_acct(args[0] as *const u8),
        Syscall::Capget => sys_capget(args[0] as *mut CapUserHeader, args[1] as *mut CapUserData),
        Syscall::Capset => sys_capset(args[0] as *mut CapUserHeader, args[1] as *const CapUserData),
        Syscall::Personality => sys_personality(args[0] as u32),
        Syscall::Chroot => sys_chroot(args[0] as *const u8),
        Syscall::Vhangup => sys_vhangup(),
        Syscall::Prctl => sys_prctl(args[0] as u32, args[1], args[2], args[3], args[4]),
        _ => {
            warn!("Unsupported syscall_id: {}!", id);
            // sys_memfd_secret(args[0] as u32)
            return Err(SysErrNo::ENOSYS);
        }
    }
}
